site_name: pysparkplus
site_author: Silvio Liborio
site_description: >-
  Extend your string powers with pyspark+  
site_url: https://wiseupdata.github.io/pysparkplus/index.html

# Copyright
copyright: Copyright &copy; 2023 - 2023 Silvio Liborio

watch: [README.md]

theme:
  name: 'material'
  # custom_dir: assets/overrides/html
  favicon: "https://raw.githubusercontent.com/wiseupdata/pysparkplus/main/assets/imgs/python.png"
  logo: "https://raw.githubusercontent.com/wiseupdata/pysparkplus/main/assets/imgs/python.png"
  palette:
    # Palette toggle for dark mode
    # - scheme: pysparkplus
    - scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-4
        name: "Switch to light mode"
    # Palette toggle for light mode
    - scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-night
        name: "Switch to dark mode"
  font:
    text: Roboto
    code: Roboto Mono
    features:
      - search.suggest
      - search.highlight
      - announce.dismiss
      - content.action.edit
      - content.action.view
      - content.code.annotate
      - content.code.copy
      - content.tooltips
      - navigation.footer
      - navigation.indexes
      - navigation.sections
      - navigation.tabs
      - navigation.top
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      - toc.follow
      - footnotes
  icon:
    repo: fontawesome/brands/github-alt
  language: en
repo_name: wiseupdata/pysparkplus
repo_url: https://github.com/wiseupdata/pysparkplus


extra_css:
  - themes/pysparkplus.css

nav:
- package: pysparkplus/
- Python file: examples/functions_01.ipynb

plugins:
  - search 
  - gen-files:
      scripts:
      - assets/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.txt
  - section-index 
  - mkdocstrings:
      handlers:
        python:
          paths: [pysparkplus]
  - mkdocs-jupyter:
     theme: slate
     show_input: True
     highlight_extra_classes: "pysparkplus"  

markdown_extensions:
- tables
- toc:
    permalink: true
    title: Pages
- admonition
- pymdownx.highlight
- pymdownx.extra
- pymdownx.tabbed:
    alternate_style: true

# language options
extra:
  alternate:
    - link: https://wiseupdata.github.io/pysparkplus/
      name: English