[tool.poetry]
name = "pyspark-functions"
version = "0.0.1"
description = ""
authors = ["wiseupdata <silvio.liborio@wiseupdata.com>"]
readme = "README.md"
packages = [{include = "pyspark_functions"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
